export const categoriesByStoreType = {
  "Grocery Store": [
    "Fresh Produce",
    "Meat & Poultry",
    "Seafood",
    "Dairy & Eggs",
    "Bread & Bakery",
    "Snacks & Chips",
    "Beverages",
    "Canned & Packaged Goods",
    "Frozen Food",
    "Rice, Pasta & Grains",
    "Condiments & Spices",
    "Cleaning Supplies",
    "Household Essentials",
    "Baby Products",
    "Pet Supplies",
  ],
  "Pharmacy": [
    "Prescription Medicines",
    "OTC Medicines",
    "Vitamins & Supplements",
    "First Aid Supplies",
    "Medical Devices",
    "Personal Care",
    "Hygiene Products",
    "Beauty & Cosmetics",
    "Baby Care",
    "Adult Care",
    "PPE & Sanitizers",
  ],
  "Clothing Store": [
    "Men’s Clothing",
    "Women’s Clothing",
    "Kids’ Clothing",
    "Baby Clothing",
    "Footwear",
    "Bags & Accessories",
    "Underwear & Socks",
  ],
  "Electronics Store": [
    "Mobile Devices",
    "Computers & Laptops",
    "Computer Accessories",
    "Phone Accessories",
    "Audio Devices",
    "Cameras & Photography",
    "Home Appliances",
    "Personal Appliances",
    "Gaming Consoles & Accessories",
    "Cables, Adapters & Chargers",
  ],
  "Hardware Store": [
    "Hand Tools",
    "Power Tools",
    "Construction Materials",
    "Electrical Supplies",
    "Plumbing Supplies",
    "Paint & Painting Supplies",
    "Gardening Tools",
    "Fasteners (Nails, Screws, Bolts)",
    "Safety Gear",
  ],
  "Bookstore": [
    "Fiction Books",
    "Non-Fiction Books",
    "Educational Books",
    "Children’s Books",
    "Comics & Manga",
    "School Supplies",
    "Art Materials",
    "Office Supplies",
    "Stationery & Gifts",
  ],
  "Convenience Store": [
    "Snacks",
    "Beverages",
    "Ready-to-Eat Food",
    "Instant Noodles / Cup Meals",
    "Frozen Food",
    "Basic Grocery Items",
    "Toiletries",
    "Basic OTC Medicines",
    "Household Essentials",
    "Phone Load",
    "Ice Cream & Desserts",
    "Tobacco & Lighters",
  ],
  "Others": [
    "Miscellaneous",
  ]
};
